version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: laravel_app
        ports:
            - "80:80"                       # Nginx trong cùng container
        environment:
            REDIS_HOST: redis
            REDIS_PORT: 6379
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: laravel
            DB_USERNAME: laravel
            DB_PASSWORD: laravel
            APP_NAME: Laravel
            APP_ENV: local
            APP_KEY: base64:5nl3Dub80DTGkXQ+RWDqW7xXngtwPYIFHu5frtrEzv8=
            APP_DEBUG: true
            APP_URL: http://localhost
            LOG_CHANNEL: stack
            LOG_DEPRECATIONS_CHANNEL: null
            LOG_LEVEL: debug
        volumes:
           - ./:/var/www
#            - ./docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:ro
        depends_on:
            - mysql
            - redis
        networks:
            - laravel

    mysql:
        image: mysql:8.0
        container_name: laravel_mysql
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel

    redis:
        image: redis:7-alpine
        container_name: laravel_redis
        ports:
            - "6379:6379"
        networks:
            - laravel

networks:
    laravel:

volumes:
    mysql_data:
